# Generated by Django 6.0.5 on 2026-05-13 10:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Carpeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('icona', models.CharField(default='bi-star-fill', max_length=50)),
                ('color', models.CharField(default='#8a2be2', max_length=20)),
                ('data_creacio', models.DateTimeField(auto_now_add=True)),
                ('usuari', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='les_meves_carpetes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Folder',
                'verbose_name_plural': 'Folders',
            },
        ),
        migrations.CreateModel(
            name='LlistaPersonal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_afegida', models.DateTimeField(auto_now_add=True)),
                ('carpeta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='lists.carpeta')),
                ('pelicula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contents.pelicula')),
                ('usuari', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='la_meva_llista', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'List item',
                'verbose_name_plural': 'List items',
                'unique_together': {('usuari', 'pelicula', 'carpeta')},
            },
        ),
    ]
