# Generated by Django 6.0.2 on 2026-02-26 16:15

from django.db import migrations, models


def initial_registries(apps, schema_editor):
    model = apps.get_model('users', 'Users')
    model.objects.create(first_name="Alejandro", last_name="Martinez")
    model.objects.create(first_name="Amancio", last_name="Smith")
    model.objects.create(first_name="Larry", last_name="Scout")
    model.objects.create(first_name="Amalia", last_name="Mendoza")

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RunPython(initial_registries)
    ]
