# Generated by Django 6.0.3 on 2026-04-21 07:55

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Carpeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('icona', models.CharField(default='bi-star-fill', max_length=50)),
                ('color', models.CharField(default='#8a2be2', max_length=20)),
                ('data_creacio', models.DateTimeField(auto_now_add=True)),
                ('usuari', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='les_meves_carpetes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Carpeta',
                'verbose_name_plural': 'Carpetes',
            },
        ),
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('titol', models.CharField(max_length=255)),
                ('director', models.CharField(blank=True, max_length=255, null=True)),
                ('sinopsi', models.TextField(blank=True, null=True)),
                ('any', models.IntegerField(blank=True, null=True)),
                ('valoracio', models.FloatField(default=0.0)),
                ('plataforma', models.CharField(blank=True, max_length=100, null=True)),
                ('classificacio_edat', models.CharField(blank=True, max_length=50, null=True)),
                ('durada', models.CharField(blank=True, max_length=50, null=True)),
                ('imatge', models.URLField(blank=True, max_length=500, null=True)),
                ('tipus', models.CharField(choices=[('movie', 'Pel·lícula'), ('series', 'Sèrie')], default='movie', max_length=20)),
                ('generes', models.ManyToManyField(blank=True, related_name='pelicules', to='users.genere')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipus', models.JSONField(blank=True, default=list)),
                ('plataformes', models.JSONField(blank=True, default=list)),
                ('generes', models.JSONField(blank=True, default=list)),
                ('edat_rating', models.JSONField(blank=True, default=list)),
                ('manager_de', models.CharField(blank=True, choices=[('CinePlus', 'CinePlus'), ('StreamHub', 'StreamHub'), ('PlayMax', 'PlayMax')], max_length=50, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Views',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visualization_date', models.DateTimeField(auto_now_add=True)),
                ('count', models.IntegerField(default=0)),
                ('pelicula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='users.pelicula')),
                ('usuari', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LlistaPersonal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_afegida', models.DateTimeField(auto_now_add=True)),
                ('carpeta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='users.carpeta')),
                ('usuari', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='la_meva_llista', to=settings.AUTH_USER_MODEL)),
                ('pelicula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.pelicula')),
            ],
            options={
                'verbose_name': 'Element de llista',
                'verbose_name_plural': 'Elements de llistes',
                'unique_together': {('usuari', 'pelicula', 'carpeta')},
            },
        ),
        migrations.CreateModel(
            name='Ressenya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntuacio', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('comentari', models.TextField(blank=True, null=True)),
                ('data_publicacio', models.DateTimeField(auto_now_add=True)),
                ('pelicula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ressenyes', to='users.pelicula')),
                ('usuari', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ressenyes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('usuari', 'pelicula')},
            },
        ),
    ]
