# Generated by Django 6.0.3 on 2026-05-12 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titol', models.CharField(max_length=200)),
                ('descripcio', models.TextField()),
                ('tipus', models.CharField(choices=[('general', 'General rating'), ('error', 'Report error'), ('suggestion', 'Suggestion'), ('other', 'Other comments')], max_length=20)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('data_creacio', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='carpeta',
            options={'verbose_name': 'Folder', 'verbose_name_plural': 'Folders'},
        ),
        migrations.AlterModelOptions(
            name='llistapersonal',
            options={'verbose_name': 'List item', 'verbose_name_plural': 'List items'},
        ),
        migrations.AddField(
            model_name='profile',
            name='manager_de',
            field=models.CharField(blank=True, choices=[('CinePlus', 'CinePlus'), ('StreamHub', 'StreamHub'), ('PlayMax', 'PlayMax')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='tipus',
            field=models.CharField(choices=[('movie', 'Movie'), ('series', 'Series')], default='movie', max_length=20),
        ),
    ]
