# Generated by Django 6.0.3 on 2026-03-17 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_delete_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='edats',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='profile',
            name='idiomes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='profile',
            name='paisos',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
