# Generated by Django 6.0.5 on 2026-05-13 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('titol', models.CharField(max_length=255)),
                ('director', models.CharField(blank=True, max_length=255, null=True)),
                ('sinopsi', models.TextField(blank=True, null=True)),
                ('any', models.IntegerField(blank=True, null=True)),
                ('valoracio', models.FloatField(default=0.0)),
                ('plataforma', models.CharField(blank=True, max_length=100, null=True)),
                ('classificacio_edat', models.CharField(blank=True, max_length=50, null=True)),
                ('durada', models.CharField(blank=True, max_length=50, null=True)),
                ('imatge', models.URLField(blank=True, max_length=500, null=True)),
                ('tipus', models.CharField(choices=[('movie', 'Movie'), ('series', 'Series')], default='movie', max_length=20)),
                ('generes', models.ManyToManyField(blank=True, related_name='pelicules', to='contents.genere')),
            ],
        ),
    ]
