# Generated by Codex on 2026-05-21

from django.db import migrations, models


def populate_platform(apps, schema_editor):
    Views = apps.get_model('analytics', 'Views')
    for view in Views.objects.select_related('pelicula').filter(plataforma__isnull=True):
        view.plataforma = view.pelicula.plataforma
        view.save(update_fields=['plataforma'])


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='views',
            name='plataforma',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.RunPython(populate_platform, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='views',
            constraint=models.UniqueConstraint(
                fields=('usuari', 'pelicula', 'plataforma'),
                name='unique_view_per_user_content_platform'
            ),
        ),
    ]
