# Generated by Django 6.0.5 on 2026-05-13 10:15

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titol', models.CharField(max_length=200)),
                ('descripcio', models.TextField()),
                ('tipus', models.CharField(choices=[('general', 'General rating'), ('error', 'Report error'), ('suggestion', 'Suggestion'), ('other', 'Other comments')], max_length=20)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('data_creacio', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ressenya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntuacio', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('comentari', models.TextField(blank=True, null=True)),
                ('data_publicacio', models.DateTimeField(auto_now_add=True)),
                ('pelicula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ressenyes', to='contents.pelicula')),
                ('usuari', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ressenyes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('usuari', 'pelicula')},
            },
        ),
    ]
