name: Django CD

on:
  push:
    branches: ["master"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy to server
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: 127.0.0.1
        username: denis
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd ../../StramSync
          git pull origin master
          source venv/bin/activate
          pip install -r requirements.txt
          python manage.py migrate
          python manage.py collectstatic --noinput
          sudo systemctl restart gunicorn
