name: Django CI

on:
  push:
    branches: ["master", "develop", "features/*"]
  pull_request:
    branches: ["master"]
  workflow_dispatch:


   # branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    environment: testing
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.12]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip install -r requirements.txt
        

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}


    - name: Docker build and push (Build stage)
      run: |
         docker build -t ${{ vars.DOCKER_USERNAME }}/streamsync-group-c:latest .
         docker save ${{ vars.DOCKER_USERNAME }}/streamsync-group-c:latest -o StreamSync.tar
         
#         docker push ${{ vars.DOCKER_USERNAME }}/streamsync-group-c:latest
        
    - name: Docker of the api (Build stage)
      run:
        |
        docker compose -f ./api/docker-compose.yaml build
        docker images
        docker save -o StreamSync.tar api-movies-api:latest api-movies-api-2:latest api-movies-api-3:latest
#        docker save api-movies.api:latest api-movies.api-2:latest api-movies.api-3:latest -o StreamSync.tar
      # Para Usar la imagen:
      #   - Extraer del artifact.
      #   - Usar los siguiente comando:
#              docker load -i StreamSync.tar # Para cargar la imagen en local
             # docker run -p 8000:8000 StreamSync:latest
    - name: Upload Docker image as an artifact
      uses: actions/upload-artifact@v4
      with:
        name: docker-image
        path: StreamSync.tar

    - name: Run Tests
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        API_BASE_URLS: ${{ secrets.PI_BASE_URLS }}

        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        DEBUG: ${{ secrets.DEBUG }}
      run: |
        python3 manage.py test
