
name: From develop to master

on:
  pull_request: 
    branches: [develop]
    types: [closed]
      

jobs:
  merge:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
          with:
            fetch-depth: 0
      - name: Merge develop into master
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

          git fetch origin
          git checkout master
          git merge origin/develop
          git push origin master
  
