name: Issues Histogram

on:
  schedule:
    - cron: "50 9 * * *"   # Cada lunes a las 3:00 AM
  workflow_dispatch:      # Permite ejecución manual

jobs:
  generate-graph:
    runs-on: ubuntu-latest

    # IMPORTANTE: Necesitamos permiso de escritura para subir el archivo al repo
    permissions:
      contents: write
      issues: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          # Esto es necesario para que el push funcione correctamente
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.11"


      - name: Install dependencies
        run: python -m pip install --upgrade pip && pip install matplotlib>=3.7.3 && pip install requests matplotlib python-decouple # comment

      - name: Run script
        working-directory: ./IshikawaTools
        env:
           HISTOGRAM_TOKEN: ${{ secrets.HISTOGRAM_TOKEN }}

        run: git pull && python ./histogram.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ishikawa-chart
          path: IshikawaTools/issues_per_week.png



#      - name: Install dependencies
#        run: |
#          python -m pip install --upgrade pip
#          pip install requests matplotlib python-decouple
#
#      - name: Run issues histogram script
#        working-directory: ./IshikawaTools
#        env:
#          HISTOGRAM_TOKEN: ${{ secrets.HISTOGRAM_TOKEN }}
#        run: python ./histogram.py
#
#      - name: Commit and Push changes
#        run: |
#          # Configurar el usuario de Git (puedes usar el bot de GitHub)
#          git config --global user.name "github-actions[bot]"
#          git config --global user.email "github-actions[bot]@users.noreply.github.com"
#
#          # Añadir el archivo generado
#          git add IshikawaTools/issues_per_week.png
#
#          # Hacer el commit solo si hay cambios
#          git commit -m "Update issues histogram graph [skip ci]" || echo "No changes to commit"
#
#          # Subir los cambios al repositorio
#          git push
