on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
  
    steps:
      - name: Cechout repo
        uses: action/checkout@v5
  
      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
  
      - name: Run script
        run: python ./scripts/runchart.py

      - name: Commit and Push changes
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: "chore(run-chart): Update generated chart image"
          commit_user_name: DenisLazarian [Github Actions]
  
